[package]
edition = "2018"
name = "ropen"
version = "0.1.0"

[profile.release]
opt-level = "z"  # Optimize for size.
lto = true

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.8", features = ["derive"] }
futures-util = "0.3.21"
infer = "0.9.0"
tarpc = { version = "0.29.0", features = ["serde-transport-bincode", "tcp", "serde-transport"] }
tempdir = "0.3.7"
thiserror = "1.0.31"
toml = "0.5.9"
serde = "1.0.138"
tokio = { version = "1.19.2", features = ["full", "tracing"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }
